FROM docker.io/library/python:3-alpine

ADD api .
ADD requirements.txt .

RUN apk update \
	&& apk upgrade \
    && apk add --no-cache gcc musl-dev mariadb-connector-c-dev \
    && pip install --upgrade pip \
    && pip install -r requirements.txt \
    && apk remove gcc muls-dev \
    && pip cache purge

 CMD ["uvicorn", "api.app:app", "--host=0.0.0.0","--port=8000","--reload"]
